# Generated by Django 4.0.2 on 2022-03-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout',
            field=models.DateField(),
        ),
    ]
