# Generated by Django 4.0.3 on 2022-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_reservation_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='available',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
